# 차선 검출 파라미터
lane_detection:
  roi_height_ratio: 0.4
  canny_low_threshold: 50
  canny_high_threshold: 150
  hough_threshold: 40
  min_line_length: 30
  max_line_gap: 50

# PID 제어 파라미터
pid_control:
  kp: 1.2
  ki: 0.1
  kd: 0.3